### ISSUE TITLE
'Booster' object has no attribute 'booster'

### ISSUE THREAD

**Issue by dping1** [dmlc/xgboost#3894]
Having an issue with a loaded model from a pickle file.  The following code was working before, but now it is going me the 'Booster' object has no attribute 'booster'

import pickle 
import xgboost as xg
loaded_model = pickle.load(open("xgboost-model", "rb"))
xg.plot_importance(loaded_model)

Full stack trace below:

AttributeErrorTraceback (most recent call last)
<ipython-input-6-27f0d8bf6762> in <module>()
----> 1 xg.plot_importance(loaded_model)

/home/ec2-user/anaconda3/envs/python2/lib/python2.7/site-packages/xgboost/plotting.pyc in plot_importance(booster, ax, height, xlim, ylim, title, xlabel, ylabel, importance_type, max_num_features, grid, show_values, **kwargs)
     66         importance = booster.get_booster().get_score(importance_type=importance_type)
     67     elif isinstance(booster, Booster):
---> 68         importance = booster.get_score(importance_type=importance_type)
     69     elif isinstance(booster, dict):
     70         importance = booster

/home/ec2-user/anaconda3/envs/python2/lib/python2.7/site-packages/xgboost/core.pyc in get_score(self, fmap, importance_type)
   1433         """
   1434 
-> 1435         if self.booster != 'gbtree':
   1436             raise ValueError('Feature importance is not defined for Booster type {}'
   1437                              .format(self.booster))

AttributeError: 'Booster' object has no attribute 'booster'

**Comment by hcho3** [comment]
Did you generate the pickle file in a previous version?

**Comment by hcho3** [comment]
#3894 should fix the issue.

**Comment by githubhnw** [comment]
Hello, 

Issue still persists!

**Comment by hcho3** [comment]
@githubhnw Please use the latest master.

**Comment by githubhnw** [comment]
@hcho3 Sorry, I'm using conda_python3 kernel, python 3.6 and latest git clone for xgboost and this error persists. What were you refering at when you commented "Did you generate the pickle file in a previous version?"? Thanks

**Comment by hcho3** [comment]
Can you post the error message?

**Comment by githubhnw** [comment]
Yes. So, I'm downloading a model artifact of XgBoost Sagemaker with extension 'tar.gz' from S3 storage in Jupyter local and use the code below to open local file and unpack it :

import tarfile
import joblib
import xgboost as xgb

# Unpack model file

tar = tarfile.open("model.tar.gz", "r:gz")
for member in tar.getmembers():
     f = tar.extractfile(member)
     if f is not None:
         content = f.read()
tar.extractall()

fil = open('xgboost-model', 'rb')

## Load model file back into generate predictions & view feature importance
xgb_local_model = joblib.load(fil)

## Close
fil.close()

And then, I try to see feature importance : 

fig, ax = plt.subplots(figsize=(6,6))
# max_num_features is 78: 26 signals and for each a roll avg for 7 and 14 days
xgb.plot_importance(xgb_local_model, height=0.8, importance_type='weight', max_num_features=78, show_values = False, ax=ax)
plt.title('XGBoost with roll avgs -  Model Feature Importance')
plt.show()

The error is : 
![image](https://user-images.githubusercontent.com/24211109/49086104-69c17800-f25c-11e8-8163-aa136404a756.png)

Thanks

**Comment by hcho3** [comment]
@githubhnw Submitted #3944 to add the missing change.

**Comment by marcusjzw** [comment]
Hi @dping1, did you ever get this working? I'm also using XGBoost on Sagemaker, trying to get out feature importances.

Sagemaker, afaik, is running XGBoost 0.72. I'm guessing we'll just have to wait until Amazon adopts a future release with this fix in it?
