### ISSUE TITLE
Rank:pairwise model crash (in R)

### ISSUE THREAD

**Issue by BlindApe** [dmlc/xgboost#413]
I'm finding problems with rank now (time ago this works fine).

```r
require(xgboost)
data(agaricus.train, package='xgboost')
train <- agaricus.train
# (data has 6513 rows. 65 queries of length 100 and one with length 13)
groups <- c(rep(100, 65), 13)
dtrain <- xgb.DMatrix(data = train$data, label = train$label, group = groups)
bst <- xgboost(dtrain, max.depth = 2, eta = .1, nround = 10, nthread = 2, objective = 'rank:pairwise')
```

**Comment by ajkl** [comment]
Seems to be working fine for me.

**Comment by BlindApe** [comment]
This is a message before crash:
Error in .signalSimpleWarning("parameter seed is ignored, please set random seed using set.seed", 'rho' must be an enviroment not language: detected in C-level eval





> sessionInfo()
R version 3.1.0 (2014-04-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                   LC_TIME=Spanish_Spain.1252    
 
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xgboost_0.4-2

loaded via a namespace (and not attached):
 [1] chron_2.3-45     data.table_1.9.4 grid_3.1.0       lattice_0.20-29  magrittr_1.5     Matrix_1.1-4     plyr_1.8.1       Rcpp_0.11.6      reshape2_1.4.1   stringr_0.6.2

**Comment by tqchen** [comment]
I see, this warning was added intentionally, seems it crashes the env. There has been a bit problem in parallel random number generations in R, which we hope to fix by optionally introducing C++11 dependencies to use standard random number.

I will update the issue when this is pushed in, in meanwhile, I pushed a temp fix to hopefully ignore the warning. Try the most recent version at github.

Thanks!

**Comment by BlindApe** [comment]
The fix works.
Thank you!

**Comment by slfan2013** [comment]
the problem still exists. When I run BlindApe's code, R Session Aborts.
