### ISSUE TITLE
Repeated runs of xgb.cv in R eventually crash

### ISSUE THREAD

**Issue by ronmexico2718** [dmlc/xgboost#717]
If I run xgb.cv multiple times in a single R session, one of the runs will inevitably get "stuck" and not complete.  The RAM and CPU usage does not appear to be excessive when the issue occurs.

I have reproduced this issue across a variety of machines (all Windows) using the newest version of xgboost.  I have included a minimal working example of this issue in the code below.

library(xgboost)
library(MASS)

n <- 300000
NModels <- 100
xg_pars <- list(eta=0.01, max.depth=3)
for (i in 1:NModels) {
  x <- mvrnorm(n=n, mu=c(0,0,0), Sigma=matrix(c(1,0,0,0,1,0,0,0,1), c(3,3)))
  y <- x[,1] ^ 2 + x[,2] ^ 2 + x[,3] ^ 2 + runif(n=nrow(x), min=-1,max=1)
  xg_model <- xgb.cv(xg_pars
                          , data = xgb.DMatrix(data.matrix(x), label=data.matrix(y), missing=NA)
                          , nrounds=6000
			  , nfold=5
			  , verbose=FALSE)
}

**Comment by terrytangyuan** [comment]
I don't have a windows machine at hand. Could anyone else the problem?

**Comment by Sandy4321** [comment]
I try to run your code
first line
t0 <- proctime()

is written wo .
would it should be t0 <- proc.time()

after this fix I still have error

Error: could not find function "xgbcv"
pls see below

> library(xgboost)
Warning message:
package ‘xgboost’ was built under R version 3.2.3
> library(MASS)
Warning message:
package ‘MASS’ was built under R version 3.2.3
> n <- 300000
> xg_pars <- list(eta=001, maxdepth=3)
> NModels <- 100
> for (i in 1:NModels) {
+ t0 <- proc.time()
+ x <- mvrnorm(n=n, mu=c(0,0,0), Sigma=matrix(c(1,0,0,0,1,0,0,0,1), c(3,3)))
+ y <- x[,1] ^ 2 + x[,2] ^ 2 + x[,3] ^ 2 + runif(n=nrow(x), min=-1,max=1)
+ xg_model <- xgbcv(xg_pars
+ , data = xgbDMatrix(datamatrix(x), label=datamatrix(y), missing=NA)
+ , nrounds=6000
+ , nfold=5
+ , verbose=FALSE)
+ }
Error: could not find function "xgbcv"

used code is
# https://github.com/dmlc/xgboost/issues/717
library(xgboost)
library(MASS)

n <- 300000
NModels <- 100
xg_pars <- list(eta=001, maxdepth=3)
for (i in 1:NModels) {
  t0 <- proc.time()
  x <- mvrnorm(n=n, mu=c(0,0,0), Sigma=matrix(c(1,0,0,0,1,0,0,0,1), c(3,3)))
  y <- x[,1] ^ 2 + x[,2] ^ 2 + x[,3] ^ 2 + runif(n=nrow(x), min=-1,max=1)
  xg_model <- xgbcv(xg_pars
                    , data = xgbDMatrix(datamatrix(x), label=datamatrix(y),
missing=NA)
                    , nrounds=6000
                    , nfold=5
                    , verbose=FALSE)
}

Regards
Sander
pld let me know what happen, since I am new in xgboost , so let make it
works together

**Comment by ronmexico2718** [comment]
Sander, it looks like the "." in xgb.cv got lost somehow.  Try changing "xgbcv" to "xgb.cv". You will also need to change "xgbDMatrix" to "xgb.DMatrix" and "datamatrix" to "data.matrix".

If anyone has a Mac, I'd be curious to see if this issue occurs on your machine.  I have not tested this on a Mac. I should mention that this code will take quite a while to run (hours or days, depending on your machine)

**Comment by Sandy4321** [comment]
super I fixed file and send to you, pls check
meantime it runs very long time
may you recommend how to short time by use simple model and then make it
more complicated step by step
this way we may find problematic point..

**Comment by ronmexico2718** [comment]
Unfortunately, I cannot recommend a way to shorten the runtime.  The problem seems to occur only training a big model multiple times.  If I use simple models, the problem does not occur.

Thanks so much for your help and let me know if there's anything else I can do to help.

Will

**Comment by ronmexico2718** [comment]
One other note.  I am running this on a machine with a 4-core processor.  When I reduce the number of processors used in the parallelization by setting nthread=2, this delays, but does not prevent, the crashing.  That is, the code will still crashing, but it will successfully train more models before crashing.  That is, when I set nthread=2, the code might crash on i=150, but when i don't set nthread=2, the code crashes around i=60

**Comment by yifanxie** [comment]
About a few weeks ago, I thought I had the same issue you reported, that XGB got stuck after running on a long cv session on windows with rstudio.

then last week I realised that even for a long but "normal" for loop, my rsession will also get stuck after 3-4 hours running.

I am more thinking this is a issue with rsession memory management, perhaps others have similar experience?

**Comment by thirdwing** [comment]
@yifanxie if you can provide a reproducible case. I might have time to look into it.

The difference of R memory management on Windows and Linux is very minor.

**Comment by ronmexico2718** [comment]
Thanks @yifanxie and @thirdwing for looking into this.  At the top of the thread I provided a reproducible example of this issues.  The code does take quite a long time to run.  Unfortunately, this is necessary.  I only receive this issue when running relatively intense computation for a long time period

**Comment by albedan** [comment]
Hi guys, I'm experiencing exactly the same problem as @yifanxie and @ronmexico2718, i.e. xgboost getting stuck after several xgb.cv runs in the same R session, typically after 6-8 hours (sometimes more, sometimes less).
I'm using Windows 7 64-bit and R studio.
Just to provide an extra information, when xgboost gets stuck there is a curious situation: I find the cpu still running at 25% (I've got a quad core cpu, that means 1 core is somehow still running).

**Comment by hetong007** [comment]
This problem might be already fixed by https://github.com/dmlc/xgboost/pull/1489.
